anh_content_block_admin:
    path: '/'
    defaults:
        _controller: anh_content_block.block.controller:dummyAction
        _anh_resource:
            view: AnhContentBlockBundle:Admin:index.html.twig

anh_content_block_admin_block_create:
    path: '/blocks/create'
    defaults:
        _controller: anh_content_block.block.controller:createAction
        _anh_resource:
            redirect: anh_content_block_admin_block_list
            view: AnhContentBlockBundle:Admin/block:create.html.twig

anh_content_block_admin_block_update:
    pattern: '/blocks/update-{id}'
    defaults:
        _controller: anh_content_block.block.controller:updateAction
        _anh_resource:
            redirect: referer
            view: AnhContentBlockBundle:Admin/block:update.html.twig
    requirements:
        id: '\d+'

anh_content_block_admin_block_delete:
    pattern: '/blocks/delete'
    defaults:
        _controller: anh_content_block.block.controller:deleteAction
        _anh_resource:
            redirect: anh_content_block_admin_block_list

anh_content_block_admin_block_list:
    pattern: '/blocks'
    defaults:
        _controller: anh_content_block.block.controller:listAction
        _anh_resource:
            view: AnhContentBlockBundle:Admin/block:list.html.twig

anh_content_block_admin_group_create:
    path: '/groups/create'
    defaults:
        _controller: anh_content_block.group.controller:createAction
        _anh_resource:
            redirect: anh_content_block_admin_group_list
            view: AnhContentBlockBundle:Admin/group:create.html.twig

anh_content_block_admin_group_update:
    pattern: '/groups/update-{id}'
    defaults:
        _controller: anh_content_block.group.controller:updateAction
        _anh_resource:
            redirect: referer
            view: AnhContentBlockBundle:Admin/group:update.html.twig
    requirements:
        id: '\d+'

anh_content_block_admin_group_delete:
    pattern: '/groups/delete'
    defaults:
        _controller: anh_content_block.group.controller:deleteAction
        _anh_resource:
            redirect: anh_content_block_admin_group_list

anh_content_block_admin_group_list:
    path: '/groups'
    defaults:
        _controller: anh_content_block.group.controller:listAction
        _anh_resource:
            view: AnhContentBlockBundle:Admin/group:list.html.twig
