anh_content_block_admin:
    path: '/'
    defaults:
        _controller: anh_content_block.block.controller:dummyAction
        _anh_resource:
            view: AnhContentBlockBundle:Admin:index.html.twig

anh_content_block_admin_block_create:
    path: '/blocks/create'
    defaults:
        _controller: anh_content_block.block.controller:createAction
        _anh_resource:
            redirect: anh_content_block_admin_block_list
            view: AnhContentBlockBundle:Admin/block:create.html.twig

anh_content_block_admin_block_update:
    pattern: '/blocks/update-{id}'
    defaults:
        _controller: anh_content_block.block.controller:updateAction
        _anh_resource:
            redirect: referer
            view: AnhContentBlockBundle:Admin/block:update.html.twig
    requirements:
        id: '\d+'

anh_content_block_admin_block_delete:
    path: '/blocks/delete'
    defaults:
        _controller: anh_content_block.block.controller:deleteAction
        _anh_resource:
            redirect: anh_content_block_admin_block_list

anh_content_block_admin_block_list:
    path: '/blocks'
    defaults:
        _controller: anh_content_block.block.controller:listAction
        _anh_resource:
            view: AnhContentBlockBundle:Admin/block:list.html.twig

anh_content_block_admin_position_list:
    path: '/positions'
    defaults:
        _controller: anh_content_block.block.controller:dummyAction
        _anh_resource:
            view: AnhContentBlockBundle:Admin:/positions.html.twig
            data:
                positions: 'container.getParameter("anh_content_block.positions")'