parameters:
    anh_content_block.entity.block.class: Anh\ContentBlockBundle\Entity\Block
    anh_content_block.form_type.block.class: Anh\ContentBlockBundle\Form\BlockType
    anh_content_block.twig.content_block_extension.class: Anh\ContentBlockBundle\Twig\ContentBlockExtension
services:
    anh_content_block.bundle:
        class: Anh\ContentBlockBundle\AnhContentBlockBundle
        factory_service: kernel
        factory_method: getBundle
        arguments:
            - 'AnhContentBlockBundle'
        tags:
            - { name: anh_admin.bundle }

    anh_content_block.form_type.block:
        class: %anh_content_block.form_type.block.class%
        arguments:
            - %anh_content_block.entity.block.class%
            - %anh_content_block.positions%
        tags:
            - { name: form.type, alias: anh_content_block_block }

    anh_content_block.twig.content_block_extension:
        class: %anh_content_block.twig.content_block_extension.class%
        arguments:
            - @request_stack
            - @anh_content_block.block.repository
        tags:
            - { name: twig.extension }
